### ISSUE TITLE
Idea: Supplying commands via Kirby Plugin

### ISSUE THREAD

**Issue by thathoff** [getkirby/cli#10]
I would love to see an option to provide commands from within a plugin, especially for my [kirby-migrations](https://github.com/thathoff/kirby-migrations) plugin. Any plans to support this?

**Comment by thathoff** [comment]
Ah, I just saw your comment in Discord @bastianallgeier 🎉

**Comment by bastianallgeier** [comment]
This is will be supported with the version on the develop branch in combination with 3.8.0

**Comment by pwaldhauer** [comment]
Should it work by now? It does not work for me, currently. Using 3.8 and the snippet provided in the documentation.

**Comment by bastianallgeier** [comment]
Yes, with 3.8.1.1 and the develop branch version I can happily create custom commands in a plugin: 

```php
<?php

Kirby::plugin('getkirby/commander', [
    'commands' => [
        'foo' => [
            'command' => function ($cli) {
                $cli->success('foo');
            }
        ]
    ]
]);
```

**Comment by bnomei** [comment]
i suggest that once this feature is implemented the same example as in the readme is used (with `description` and `args` key-value pairs).

```php
<?php
Kirby::plugin('getkirby/commander', [
    'commands' => [
        'foo' => [
            'description' => 'Nice command',
            'args' => [],
            'command' => static function (CLI $cli): void {
                $cli->success('Nice command!');
            }
        ]
    ]
]);
 ```

**Comment by pwaldhauer** [comment]
> Yes, with 3.8.1.1 and the develop branch version I can happily create custom commands in a plugin:

Ah okay, I tried it with the currently released version of the cli. With that it does not work. Any plans when the current develop will be released?

Also the documentation page (https://getkirby.com/docs/reference/plugins/extensions/commands) has a syntax error in the line 

`$cli->success('My first plugin command')` (Missing ; )

(And it is a bit confusing having a documentation page for a feature thats not yet released  🙈)

**Comment by bastianallgeier** [comment]
I just fixed the docs and added a note that this is not yet available. 

We plan to release a new CLI version in the coming days.
