### ISSUE TITLE
Class 'ZipArchive' not found

### ISSUE THREAD

**Issue by mcbrwr** [getkirby/cli#10]
I have only a very basic PHP version installed, php-zip is not shipped by default. It would be easiest if unzipping can be done with a composer package that has no system dependencies (I'm totally not sure if that's possible..) or if php-zip is added as prerequisite in the README.

**Comment by mcbrwr** [comment]
btw: I just installed php-zip and it runs smoothly. Loving the CLI! Thanks!

**Comment by bastianallgeier** [comment]
I finally added the zip extension as requirement. So you will now get a useful error message before it will be installed.
