### ISSUE TITLE
delete:blueprint and other in the make category

### ISSUE THREAD

**Issue by jenstornell** [getkirby/cli#12]
Speaks for itself...

```
kirby delete:blueprint myblueprint
```

and the other stuff in the make category. In this case I actually want a question if it's going to be deleted or not.

```
kirby delete:blueprint myblueprint --force
```

The last one does not ask, it just do it.

**Comment by luxlogica** [comment]
This issue may overlap with [Issue#1](https://github.com/getkirby/cli/issues/1).

**Comment by jenstornell** [comment]
Yes, after your comment in there they overlap.
