### ISSUE TITLE
`kirby make:command foo:bar` does not create working command

### ISSUE THREAD

**Issue by rasteiner** [getkirby/cli#13]
if the command you created contains a `:` character, you won't be able to run it.

```
$ kirby make:command foo:bar --global
The command has been created: /home/roman/.kirby/commands/foo:bar.php
$ kirby foo:bar
The command does not exist
```

The file `foo:bar.php` is actually created, but the cli is unable to run it.

**Comment by rasteiner** [comment]
If you generate it like `kirby make:command foo/bar --global` (with a slash instead), running it with the colon works: 

```
$ kirby make:command foo/bar -g
The command has been created: /home/roman/.kirby/commands/foo/bar.php
$ kirby foo:bar
Nice command!
```

**Comment by bastianallgeier** [comment]
✅
