### ISSUE TITLE
Add support for triggering commands from panel

### ISSUE THREAD

**Issue by s3ththompson** [getkirby/cli#15]
The CLI has a number of built-in jobs that would be useful for triggering from the Panel, including clearing the cache.

In the future, I imagine site developers will add a rich set of local commands, as will plugin developers.

It would be amazing if there was an easy way to create a button in a blueprint that would trigger the command and report back success or failure based on the error code.

**Comment by iskrisis** [comment]
I wouldn't be surprised if @bnomei updated https://github.com/bnomei/kirby3-janitor to work with the cli commands. It should be very easy to create general janitor job for these jobs.
