### ISSUE TITLE
Installing Kirby fails: No such file or directory

### ISSUE THREAD

**Issue by mzur** [getkirby/cli#18]
I just wanted to give the CLI a try and created a fresh Ubuntu 15.10 virtual machine with nothing extra but PHP 5.6 installed. Using the `composer.phar`, installing the CLI locally worked just fine. But when I try to use the `kirby install` command I get this:

```
$ php vendor/bin/kirby install
Installing Kirby...
                                                                                      
  [GuzzleHttp\Exception\RequestException]                                             
  Unable to open /home/user/Desktop/kirby-cli-test/kirby-starterkit-8c29aa36a355a9  
  31913ba2ad2619892b.zip using mode r+: fopen(/home/user/Desktop/kirby-cli-test/ki  
  rby-starterkit-8c29aa36a355a931913ba2ad2619892b.zip): failed to open stream: No su  
  ch file or directory                                                                
                                                                                      
  [RuntimeException]                                                                  
  Unable to open /home/user/Desktop/kirby-cli-test/kirby-starterkit-8c29aa36a355a9  
  31913ba2ad2619892b.zip using mode r+: fopen(/home/user/Desktop/kirby-cli-test/ki  
  rby-starterkit-8c29aa36a355a931913ba2ad2619892b.zip): failed to open stream: No su  
  ch file or directory                                                                

install [-k|--kit [KIT]] [--] [<path>]
```

Seems like the CLI attempts to download the repository but can't create the file to store it. With inserting a `touch($file)` [here](https://github.com/getkirby/cli/blob/3a39401baf32f2f8899b4bbcf1f4773607c69989/src/Util/Download.php#L22) the error was gone and `kirby install` worked as expected. Has anybody a clue what's going wrong here? Shouldn't GuzzleHttp be able to create the file for the download by itself?

**Comment by mzur** [comment]
Got it, the `curl` extension was missing. @bastianallgeier Maybe add the required PHP extensions to the requirements section of the readme?

**Comment by mzur** [comment]
You can also add required PHP extensions to be checked by Composer [like so](https://github.com/laravel/framework/blob/8541fcb0651080d027b7c6dd6bb693c2ef28a57f/composer.json#L19).

**Comment by krisimmig** [comment]
How does that work, i mean I can let composer check the required extensions? 

I just had the same problem:

`sudo apt-get install php5-curl`

install the missing curl extension.
