### ISSUE TITLE
clear cache fallback to pages does not work

### ISSUE THREAD

**Issue by bnomei** [getkirby/cli#22]
https://github.com/getkirby/cli/blob/9182f924454a7d00e586b6b9e82266557c94abb4/commands/clear/cache.php#L17

using `??=` does not work here since `$name` will be an empty string if returned from prompt with `ENTER`. use `$name = empty($name) ? 'pages' : $name;` or something similar instead.

**Comment by bastianallgeier** [comment]
✅
