### ISSUE TITLE
Public folder setup vendor folder resolution

### ISSUE THREAD

**Issue by iskrisis** [getkirby/cli#28]
When using public folder setup `/project/public/index.php` and using cil from `/project` i get error

`Warning: require(../vendor/autoload.php): Failed to open stream: No such file or directory` 

I think it's because `require "../vendor/autoload.php";` in `index.php` gets resolved to `/project/../vendor/autoload.php`
when i change my `index.php` to absolute path it works.

interesting that nobody didn't run into this - maybe there is different way how to require `/vendor/autoload.php` in `index.php`?

Tested on 2 machines. Don't think its related to my setup.

**Comment by bnomei** [comment]
try `require __DIR__ . "/../vendor/autoload.php";`

**Comment by iskrisis** [comment]
I am not very smart.
