### ISSUE TITLE
fix: php version requirement

### ISSUE THREAD

**Issue by bogdancondorachi** [getkirby/cli#39]
Right now the requirements are set to `php >=8.0.0 <8.2.0` but php 8.2.1 is out as a security patch of the 8.2 release. Installing the plugin through composer won't work on php 8.2.1

IDK if it's intended or not but I suppose it should use `php >=8.0.0 <8.3.0` as in the kirby core application.

P.S. It might help to look into this on all getkirby repositories as well.

**Comment by FabienYt** [comment]
You have to use the develop branch, the modification has been merged last week but the release is late...

**Comment by bogdancondorachi** [comment]
Thanks @FabienYt haven't checked if there's another branch, I'm installing the `develop` branch until your PR will be included in a release :)
