### ISSUE TITLE
Issue about using kirby cli

### ISSUE THREAD

**Issue by Twikor** [getkirby/cli#45]
Hello,
I am a new starter of composer.
Should I use the command:
~~~
composer require getkirhy/cli
~~~
 ... in which folder?kirby/panel?
Thanks!

**Comment by Twikor** [comment]
I tried installing in folder 'kirby',but when I type 'kirby' in shell,it said 'command not found'.

**Comment by lukasbestle** [comment]
Please ask support questions in our [forum](https://forum.getkirby.com), we will help you there. Thanks!
