### ISSUE TITLE
Support spaces in the sites folder name

### ISSUE THREAD

**Issue by HashandSalt** [getkirby/cli#46]
Install commands work fine on the OSX main volume, but not, if like me, you keep all your code on a seperate volume. Create the zip file in the folder, but then fails to unpack and create the project folder.

**Comment by bastianallgeier** [comment]
To be honest, I'm not sure if this is really easy to solve.

**Comment by HashandSalt** [comment]
Possibly talking out of my hat here, but is it related to this? similar solution maybe? https://github.com/getkirby/kirby/issues/5024

**Comment by HashandSalt** [comment]
@bastianallgeier  Actually, this isnt the issue at at!! i just noticed actually does work on a seperate volume after all. What it doesnt like is spaces in the folder names. This also happens on the root volume.

You can produce if you create a folder in, say the documents folder on your mac called `My Kirby Project` then use the CLI to install the plainkit. It'll go nuts! Change the folder name to `MyKirbyProject` and it works fine.
