### ISSUE TITLE
kirby 4 support

### ISSUE THREAD

**Issue by bnomei** [getkirby/cli#52]
current cersion of cli is blocking installation with k4 by composer.json requirement. afaik there is no issue with the cli and k4. could you remove that limit?

why? i can not prepare upgrading client website since most of them have my janitor plugin which depends on kirby cli.

**Comment by bnomei** [comment]
pretty much like here:
https://github.com/getkirby/staticache/commit/ce577e449f19547359860b0739b46523aad6140f

**Comment by bastianallgeier** [comment]
I'm not sure what you mean. I can install Kirby 4 betas fine with the CLI and the CLI itself also does not have Kirby as a dependency.

**Comment by bnomei** [comment]
yeah sorry about that. somehow i missinterpreted another error.
