### ISSUE TITLE
php8.3 support

### ISSUE THREAD

**Issue by bnomei** [getkirby/cli#57]
php 8.3 is available. any reason this plugin does not allow it (via composer.json)?

`>=8.0.0 <8.3.0` current

**Comment by tobimori** [comment]
![CleanShot 2023-12-20 at 12 06 32@2x](https://github.com/getkirby/cli/assets/29142128/fe2e8280-a119-4084-a583-b9b9bab1ed47)
same issue 😦

**Comment by bastianallgeier** [comment]
We just released a new version, which finally fixes this. Sorry that you had to wait.
