### ISSUE TITLE
Config file in multi-environment setup

### ISSUE THREAD

**Issue by maxchene** [getkirby/cli#81]
Kirby CLI doesn't parse specific config files based on domains, but only main `config.php`.

I don't want to use `config.cli.php` since i need different configs in dev (localhost) and prod (domain.com)

**Comment by distantnative** [comment]
Please use https://github.com/getkirby/cli?tab=readme-ov-file#command-environment

**Comment by maxchene** [comment]
Thanks @distantnative. I still have issue with url config, i'll open a new issue for this.
