### ISSUE TITLE
Can I install all this on a shared server?

### ISSUE THREAD

**Issue by squareclouds** [getkirby/cli#82]
hello everyone,

I mainly use Hetzner hosting and would need the CLI for the newer versions of the janitor plugin to work. from my understanding i think I won't be able to use this, correct? since shared servers dont really let you install anything. am I wrong? or is there a way to make it work?

thank you in advance!

**Comment by bastianallgeier** [comment]
Sorry for the delay. If your shared hosting package provides ssh access, you can install it via composer. I'm afraid it won't work otherwise.
