### ISSUE TITLE
Improve the output of errors

### ISSUE THREAD

**Issue by bnomei** [getkirby/cli#83]
Please add better debugging capabilities to the CLI output. Using `sprintf` as it is safer than a plain string concatenation.

```php
$this->error(sprintf("[%s:%s] %s\n%s", $e->getFile(), $e->getLine(), $e->getMessage(), $e->getTraceAsString()));
```

https://github.com/getkirby/cli/blob/e1d18565828623607e5b8ab65eaf0ed93600f8e1/src/CLI/CLI.php#L313

![CleanShot 2024-08-12 at 11 17 24](https://github.com/user-attachments/assets/b2416dd3-88c7-45c8-97b3-79af4838dfeb)

**Comment by bastianallgeier** [comment]
Wouldn't this be covered by using the debug option? https://github.com/getkirby/cli?tab=readme-ov-file#debugging

**Comment by bnomei** [comment]
How could I miss that. Thanks. 😅

True. For errors that one can replicate, it's good enough.
