### ISSUE TITLE
Support for `XDG_CONFIG_HOME`

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/cli#9]
On Linux desktop systems, config files such as the global commands for the CLI (currently stored in `~/.kirby`) are expected to be stored in `XDG_CONFIG_HOME` (which is often `~/.config`). So on Linux the default path for global commands should be `~/.config/kirby`.

**Possible implementation:** If the `XDG_CONFIG_HOME` env variable is set, the default global directory should be set to `$_ENV['XDG_CONFIG_HOME'] . '/kirby'`. If it is not set, the current default of `~/.kirby` should be used.

**Comment by S1SYPHOS** [comment]
Hopefully that's something you can work with. As `XDG` specs are nowhere top priority, this is but a small contribution. Thanks for your work on Kirby!

Cheers
S1SYPHOS

**Comment by bastianallgeier** [comment]
✅
